<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Nationality extends Model
{
    /**
     * The attributes that are NOT mass assignable.
     *
     * @var array
     */
    protected $guarded = [
        'id',
    ];
    /**
     * The attributes that are NOT mass assignable.
     *
     * @var array
     */


    public static function gitNationalities()
    {

        $nationalities = [
            '1'=>["Afghan" => "أفغانستان"],
            '2'=>["Albanian" => "ألبانيا"],
            '3'=>["Algerian" => "الجزائر"],
            '4'=>["American" => "أمريكا"],
            '5'=>["Andorran" => "أندورا"],
            '6'=>["Angolan" => "أنغوليا"],
            '7'=>["Antiguans" => "انتيغوا"],
            '8'=>["Argentinean" => "الأرجنتين"],
            '9'=>["Armenian" => "أرمينيا"],
            '10'=>["Australian" => "أستراليا"],
            '11'=>["Austrian" => "النمسا"],
            '12'=>["Azerbaijani" => "أذربيجان"],
            '13'=>["Bahamian" => "باهاما"],
            '14'=>["Bahraini" => "البحرين"],
            '15'=>["Bangladeshi" => "بنغلاديش"],
            '16'=>["Barbadian" => "باربادوس"],
            '17'=>["Barbudans" => "بربودا"],
            '18'=>["Botswana" => "بوتسوانا"],   //مكرره
            '19'=>["Belarusian" => "بيلاروسيا"],
            '20'=>["Belgian" => "بلجيكا"],
            '21'=>["Belizean" => "بليز"],
            '22'=>["Beninese" => "بنين"],
            '23'=>["Bhutanese" => "بوتان"],
            '24'=>["Bolivian" => "بوليفيا"],
            '25'=>["Bosnian" => "بوسنه"],
            '26'=>["Brazilian" => "البرازيل"],
            '27'=>["British" => "بريطانيا"],
            '28'=>["Bruneian" => "بروناي"],
            '29'=>["Bulgarian" => "بولغاريا"],
            '30'=>["Burkinabe" => "بوركينا فاسو"],
            '31'=>["Burmese" => "بورما"],
            '32'=>["Burundian" => "بوروندي"],
            '33'=>["Cambodian" => "كمبوديا"],
            '34'=>["Cameroonian" => "الكاميرون"],
            '35'=>["Canadian" => "كندا"],
            '36'=>["Cape Verdean" => "الرأس الأخضر"],
            '37'=>["Central African" => "جمهورية أفريقيا الوسطى"],
            '38'=>["Chadian" => "تشاد"],
            '39'=>["Chilean" => "تشيلي"],
            '40'=>["Chinese" => "الصين"],
            '41'=>["Colombian" => "كولومبيا"],
            '42'=>["Comoran" => "جزر القمر"],
            '43'=>["Congolese" => "جمهورية الكونغو الديموقراطية"],
            '44'=>["Costa Rican" => "كوستاريكا"],
            '45'=>["Croatian" => "كرواتيا"],
            '46'=>["Cuban" => "كوبا"],
            '47'=>["Cypriot" => "القبرص"],
            '48'=>["Czech" => "تشيك"],
            '49'=>["Danish" => "الدانمارك"],
            '50'=>["Djibouti" => "جيبوتي"],
            '51'=>["Dominican" => "الدومينيكان"],
            '52'=>["Dutch" => "هولندا"],
            '53'=>["East Timorese" => "تيمور الشرقية"],
            '54'=>["Ecuadorean" => "الإكوادور"],
            '55'=>["Egyptian" => "مصر"],
            '56'=>["Emirian" => "الإمارات"],
            '57'=>["Equatorial Guinean" => "غينيا الإستوائية"],
            '58'=>["Eritrean" => "إريتريا"],
            '59'=>["Estonian" => "إستونيا"],
            '60'=>["Ethiopian" => "إثيوبيا"],
            '61'=>["Fijian" => "فيجي"],
            '62'=>["Filipino" => "الفلبين"],
            '63'=>["Finnish" => "فنلندا"],
            '64'=>["French" => "فرنسا"],
            '65'=>["Gabonese" => "الجابون"],
            '66'=>["Gambian" => "غامبيا"],
            '67'=>["Georgian" => "جورجيا"],
            '68'=>["German" => "ألمانيا"],
            '69'=>["Ghanaian" => "غانا"],
            '70'=>["Greek" => "اليونان"],
            '71'=>["Grenadian" => "جرينادا"],
            '72'=>["Guatemalan" => "غواتيمالا"],
            '73'=>["Guinea-Bissauan" => "غينيا بيساو"],
            '74'=>["Guinean" => "غينيا"],
            '75'=>["Guyanese" => "غويانا"],
            '76'=>["Haitian" => "هايتي"],
            '77'=>["Herzegovinian" => "الهرسك"],
            '78'=>["Honduran" => "هندوراس"],
            '79'=>["Hungarian" => "هنغاريا"],
            '80'=>["I-Kiribati" => "كيريباتي"],
            '81'=>["Icelander" => "ايسلندا"],
            '82'=>["Indian" => "الهند"],
            '83'=>["Indonesian" => "اندونيسيا"],
            '84'=>["Iranian" => "ايران"],
            '85'=>["Iraqi" => "العراق"],
            '86'=>["Irish" => "جمهورية ايرلندا"],
            '87'=>["Israeli" => "إسرائيل"],
            '88'=>["Italian" => "إيطاليا"],
            '89'=>["Ivorian" => "ساحل العاج"],
            '90'=>["Jamaican" => "جامايكا"],
            '91'=>["Japanese" => "اليابان"],
            '92'=>["Jordanian" => "الاردن"],
            '93'=>["Kazakhstani" => "كازاخستان"],
            '94'=>["Kenyan" => "كينيا"],
            '95'=>["Kittian and Nevisian" => "سانت كيتس ونيفيس"],
            '96'=>["Kuwaiti" => "كويت"],
            '97'=>["Kyrgyz" => "قيرغيزستان"],
            '98'=>["Laotian" => "لاوس"],
            '99'=>["Latvian" => "لاتفيا"],
            '100'=>["Lebanese" => "لبنان"],
            '101'=>["Liberian" => "ليبيريا"],
            '102'=>["Libyan" => "ليبيا"],
            '103'=>["Liechtensteiner" => "ليختنشتاين"],
            '104'=>["Lithuanian" => "لتوانيا"],
            '105'=>["Luxembourger" => "لوكسمبورغ"],
            '106'=>["Macedonian" => "مقدونيا"],
            '107'=>["Malagasy" => "مدغشقر"],
            '108'=>["Malawian" => "مالاوي"],
            '109'=>["Malaysian" => "ماليزيا"],
            '110'=>["Maldivan" => "المالديف"],
            '111'=>["Malian" => "مالي"],
            '112'=>["Maltese" => "مالطا"],
            '113'=>["Marshallese" => "جزر المارشال"],
            '114'=>["Mauritanian" => "موريتانيا"],
            '115'=>["Mauritian" => "موريشيوس"],
            '116'=>["Mexican" => "المكسيك"],
            '117'=>["Micronesian" => "ميكرونيزيا"],
            '118'=>["Moldovan" => "مولدوفا"],
            '119'=>["Monacan" => "موناكو"],
            '120'=>["Mongolian" => "منغوليا"],
            '121'=>["Moroccan" => "المغرب"],
            '122'=>["Mosotho" => "ليسوتو"],
            '123'=>["Botswana" => "بوتسوانا"],  //مكرره
            '124'=>["Motswana" => ""],
            '125'=>["Mozambican" => "موزمبيق"],
            '126'=>["Namibian" => "ناميبيا"],
            '127'=>["Nauruan" => "ناورو"],
            '128'=>["Nepalese" => "النيبال"],
            '129'=>["New Zealander" => "نيوزيلندا"],
            '130'=>["Nicaraguan" => "نيكاراغوا"],
            '131'=>["Nigerian" => "نيجيريا"],
            '132'=>["Nigerien" => "النيجر"],
            '133'=>["North Korean" => "كويا الشمالية"],
            '134'=>["Northern Irish" => "ايرلندا الشمالية"],
            '135'=>["Norwegian" => "النرويج"],
            '136'=>["Omani" => "عمان"],
            '137'=>["Pakistani" => "باكستان"],
            '138'=>["Palauan" => "بالاو"],
            '139'=>["Panamanian" => "بنما"],
            '140'=>["Papua New Guinean" => "بابوا غينيا الجديدة"],
            '141'=>["Paraguayan" => "باراغواي"],
            '142'=>["Peruvian" => "بيرو"],
            '143'=>["Polish" => "بولندا"],
            '144'=>["Portuguese" => "البرتغال"],
            '145'=>["Qatari" => "قطر"],
            '146'=>["Romanian" => "رومانيا"],
            '147'=>["Russian" => "روسيا"],
            '148'=>["Rwandan" => "رواندا"],
            '149'=>["Saint Lucian" => "سانت لوسيا"],
            '150'=>["Salvadoran" => "سلفادور"],
            '151'=>["Samoan" => "ساموا"],
            '152'=>["San Marinese" => "سان مارينو"],
            '153'=>["Sao Tomean" => "ساو تومي"],
            '154'=>["Saudi" => "السعودية"],
            '155'=>["Scottish" => "اسكتلندا"],
            '156'=>["Senegalese" => "السنغال"],
            '157'=>["Serbian" => "صربيا"],
            '158'=>["Seychellois" => "سيشل"],
            '159'=>["Sierra Leonean" => "سيراليون"],
            '160'=>["Singaporean" => "سنغافورة"],
            '161'=>["Slovakian" => "سلوفاكيا"],
            '162'=>["Slovenian" => "سلوفينيا"],
            '163'=>["Solomon Islander" => "جزر سليمان"],
            '164'=>["Somali" => "الصومال"],
            '165'=>["South African" => "جنوب افريقيا"],
            '166'=>["South Korean" => "كوريا الجنوبية"],
            '167'=>["Spanish" => "اسبانيا"],
            '168'=>["Sri Lankan" => "سريلانكا"],
            '169'=>["Sudanese" => "السودان"],
            '170'=>["Surinamer" => "سورينام"],
            '171'=>["Swazi" => "سوازيلاند"],
            '172'=>["Swedish" => "السويد"],
            '173'=>["Swiss" => "سويسرا"],
            '174'=>["Syrian" => "سوريا"],
            '175'=>["Taiwanese" => "تايوان"],
            '176'=>["Tajik" => "طاجيكستان"],
            '177'=>["Tanzanian" => "تنزانيا"],
            '178'=>["Thai" => "تايلاند"],
            '179'=>["Togolese" => "توغو"],
            '180'=>["Tongan" => "تونجا"],
            '181'=>["Trinidadian/Tobagonian" => "ترينيداد / توباغو"],
            '182'=>["Tunisian" => "تونس"],
            '183'=>["Turkish" => "تركيا"],
            '184'=>["Tuvaluan" => "توفالو"],
            '185'=>["Ugandan" => "أوغندا"],
            '186'=>["Ukrainian" => "اوكرانيا"],
            '187'=>["Uruguayan" => "اوروغواي"],
            '188'=>["Uzbekistani" => "أوزباكستان"],
            '189'=>["Venezuelan" => "فنزويلا"],
            '190'=>["Vietnamese" => "فيتنام"],
            '191'=>["Welsh" => "ويلز"],
            '192'=>["Yemenite" => "اليمن"],
            '193'=>["Zambian" => "زامبيا"],
            '194'=>["Zimbabwean" => "زيمبابوي"],

        ];
        return $nationalities;
        $nationalitiesArr = array();
        foreach ($nationalities as $en_name => $ar_name) {
            if (\App::isLocale('ar')) {
                array_push($nationalitiesArr, $ar_name);
            } else {
                array_push($nationalitiesArr, $en_name);
            }
            return $nationalitiesArr;
        }
    }




}
